package com.proyectoCM.myapplication.entidades

class RegistroBE(val id:String?=null,
                 val Usuario:String?=null,
                 val iTurno:Int?=0,
                 val sTurno:String?=null,
                 val iTipo:Int?=0,
                 val sTipo:String?=null,
                 val iEquipo:Int?=null,
                 val sEquipo:String?=null,
                 val SistemaHidraPU:String?=null,
                 val SistemaHidraObsPU:String?=null,
                 val AirePU:String?=null,
                 val AireObsPU:String?=null,
                 val CabinaPU:String?=null,
                 val CabinaObsPU:String?=null,
                 val TableroPU:String?=null,
                 val TableroObsPU:String?=null,
                 val HoroIni:Int?=0,
                 val SistemaHidraU:String?=null,
                 val SistemaHidraObsU:String?=null,
                 val AireU:String?=null,
                 val AireObsU:String?=null,
                 val CabinaU:String?=null,
                 val CabinaObsU:String?=null,
                 val TableroU:String?=null,
                 val TableroObsU:String?=null,
                 val Comentario:String?=null,
                 val HoroFin:Int?=0,
                 val Firma:String?=null,
                 val Estado:String?=null,
                 val Fecha:String?=null) {

}